GoogleCloudPlatform/terraform-python-testing-helper

- CHANGELOG.md
- test/test_args.py
- tftest.py
I have a use case where I cannot delete all resources on destroy. So that terraform behaves nicely I need to limit the resources when using the target option.
Hopefully this looks good to you, otherwise let me know if you want me to implement any more tests, etc.
> add support for target option

- test/fixtures/plan_no_resource_changes/main.tf
- test/test_plan.py
- tftest.py
Fix for #26 tftest failed when terraform plan is empty
> Don't fail when resource_changes key not present in output

- test/test_files.py
- tftest.py
master does not run on Windows (in general) for two reasons:
1. Windows is fussy about creating symlinks. You need to be running with admin privileges, or in Win 10 Developer Mode.
2. Temporary files are being created for Terraform to open (e.g. -out X) and the handles are being held on to by NamedTemporaryDirectory so it can delete the file later. Terraform on Windows does not like this, it wants exclusive access to the file (which is a Windows thing, not a Terraform thing as I understand it).
(1) is resolved by modifying TerraformTest to copy 'extra_files' if we detect we're running on Windows, track successfully copied files, and deleting them in the cleanup routine. This is made overly complex because the existing behaviour cleans up symlinked files that already existed but preserves …
> Windows fixes

- CHANGELOG.md
- test/fixtures/plan_no_resource_changes/main.tf
- test/fixtures/plan_no_variables/outputs.tf
- test/test_args.py
- test/test_plan.py
- test/test_sample_apply.py
- test/test_tg_all.py
- tftest.py
I merged master into the branch and fixed a few things - now I am able to run all the tests and passed
> Terragrunt support

- tftest.py
Adding the onerror to change the file permission then attempt the delete again fixes the issue reported in #37.
> fix: On windows if a file is read only the cleanup reports errors.

- test/fixtures/prevent_destroy/main.tf
- test/fixtures/prevent_destroy/module/main.tf
- test/test_prevent_destroy.py
- tftest.py
This is a proposal to fix the issue described in #42 
I have used features introduced in Python 3.5 and added a check in case people are using older versions of Python. If you think this needs to work on any version of Python 3 I'm happy to change the approach.
I have also only tested on MacOS, I assume in CI the tests ran under Linux. I'll try to get one of my colleagues who works on Windows to test this.
> feat: Add ability to disable lifecycle prevent_destroy

- tftest.py
Use os.path.isabs(path) instead of path.startswith('/')
> Fix _abspath for windows

- tftest.py
Fix double close on Windows 10.0.19044 N/A Build 19044.
Exception in thread Thread-1:
Traceback (most recent call last):
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
self.run()
File "C:\Users\G000737\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1267, in _readerthread
buffer.append(fh.read())
ValueError: I/O operation on closed file.
> Fix double close on Windows 10

- test/test_pickle.py
- tftest.py
The changes introduced allow `tftest.TerraformPlanOutput` and `tftest.TerraformState` instances to be [pickled](https://docs.python.org/3/library/pickle.html#pickle.Pickler). Given the above classes have custom `__getattr__` methods, the classes need `__getstate__` and `__setstate__` methods in order for `pickle.dumps()` to properly serialize the instances. In addition, in order for the serialized objects to be deserialized, the `TerraformValueDict.__getattr__` method needs to skip looking up dunder methods during `pickle.loads()` or else the method keeps calling itself resulting in a recursive loop.
If you're wondering what the use case of this functionality is, I'm currently creating caching fixtures for the outputs of tftest methods so that the output is available between pytest …
> add ability to pickle tftest instance objects

- tftest.py
When Terraform crashes the error code is 11 not 1.
> fix: Handle terraform crashes

- DEV-REQUIREMENTS.txt
- README.md
- test/test_cache.py
- tftest.py
This PR fixes the issue of the caching feature having too broad of parameters that are being used for generating the caching value. 
The current implementation uses the entire environment variable dictionary which includes test-level environment variables (e.g. `PYTEST_CURRENT_TEST`). This results in the cache being not used if a subsequent pytest test session were to be called with a different test that still requires the same tftest instance. To solve this, an internal `_env` attribute is set within `__init__` that defines the env vars that the tftest instance was initiated with. This attribute will be used instead of the `env` attribute. 
In addition, the file contents within `tfdir` and any `tf_var_file` or `extra_files` method arguments are used for generating the caching value. This …
> Finer grained cache hash input

- DEV-REQUIREMENTS.txt
- tftest.py
Replaces the `checksumdir.dirhash()` method with an internal `TerraformTest._dirhash()` method. This removes the `checksumdir` package requirement to keep tftest lightweight and portable as requested [here](https://github.com/GoogleCloudPlatform/terraform-python-testing-helper/pull/60#issuecomment-1298243927)
> Replace cache checksumdir pypi pkg with internal _dirhash()

- tftest.py
Inhering from collections.abc.Mapping gives us `__contains__`, `keys`, `items`, `values`, `get`, `__eq__`, and `__ne__` for free. It also makes objects behave more dict-like
> Inherit TerraformJSONBase from Mapping ABC

- tftest.py
- Fix basename lookup within `TerraformTest._dirhash()`
- Add `ignore_hidden` argument to the nested call to `TerraformTest._dirhash()`
> Cache hidden dir bug

- test/test_cache.py
- tftest.py
The current implementation creates the cache hash value before running the terraform or terragrunt command. If the command creates any files within the `tfdir` directory then the cache will not be used for the subsequent call since the hash value is dependent on the contents of the `tfdir`. This is seen for example with the `terragrunt init` command that produces a `.terragrunt-cache` directory. To ensure that this directory is considered for the hash, the hash is now generated also after the command is executed.
> Create cache hash after command

- test/test_args.py
- tftest.py
https://github.com/GoogleCloudPlatform/terraform-python-testing-helper/issues/68
added support to pass a complex dict to the tf_vars parameter
Like that:
`tf_vars = { "pep_spec": { "pep1": "test", "list": [ "item1", "item2" ] }, "list2": [ "item1", "item2" ] }`
> [feature] added support to pass a complex dict

- tftest.py
Adds support for specifying the state file (https://developer.hashicorp.com/terraform/language/settings/backends/local#command-line-arguments) during `plan`. This is very useful for setting up test cases for, "what if I modified this attribute on an already provisioned resource?". It is possible to achieve the same thing today using `init_vars` during `setup`, but that introduces modifies the `init` cache key and hence requires an `init` per test case using a state file. Using the plan feature affects only the plan cache key, so saves some time overall.
> Parse state flag

- tftest.py
The existing logic for building the cache directory path assumes *nix style paths when attempting to make a unique cache dir for each test fixture and step. Paths with a Windows drive prefix on the front ("C:\\...") muck this up. Pathlib's '/' operator silently covers this up (under Python 3.9 on Windows, at least).
This change _reasonably_ preserves the uniqueness logic whilst being Window friendly by taking a hash of the path to the test fixture's configuration directory `tfdir` and using that in the cache directory path construction.
> Make cache directory path Windows friendly

- tftest.py
Terraform CLI runs sometimes only produce output on stderr, or writes its final output to stderr. Tests for variable validation conditions and pre/post conditions often elicit this behaviour. On Windows 10 and Python 3.9, this leads to a hang. Line 714 (in this PR) is a blocking operation that will never be satisfied given no further standard output will be observed.
This PR hacks around it when running on Windows by redirecting stderr to stdout. This truly is a hack, because later logic from line 724 onwards assumes `err` will contain stderr but will now always be empty. In practice, this seems to work on Windows OK.
A better solution might be to do something like https://stackoverflow.com/a/4896288. This pushes my limited python-fu.
> Stop Windows hangs when last output is on stderr

- test/fixtures/apply/main.tf
- test/fixtures/apply/template.tftpl
- tftest.py
Replace deprecated template_file datasource from template provider with templatefile built-in function in pytest fixture.
> Clean up terraform runtime files
